### ISSUE TITLE
Closures required for `reduce` and `fold` methods

### ISSUE THREAD

**Issue by mathstuf** [nikomatsakis/rayon#156] opened 2016-11-17 16:46 UTC
The `Iterator::fold` method takes a single instance of the initial object whereas `ParallelIterator::reduce` method takes a closure. This means that an initial object can't be used just as easily as the `Iterator::fold` method if it is not easily constructable (e.g., some other intermediate computation).

**Comment by cuviper** [comment] 2016-11-17 18:47
There is a `ParallelIterator::fold` which takes a *constructor* for an initial object.  That will be called for every parallel split, and then you still have to `reduce` the folded results.

But in general, no, there's not any method that takes a single initial object.  There's not really any way to use such a thing in parallel, unless it's `Sync`, which means it would have to manage some interior mutability.  If you really need this, you could wrap it in a mutex like [this map_collect test](https://github.com/nikomatsakis/rayon/blob/b322af2c212380a1ed2d21a28227e9d91d3d4b2f/rayon-demo/src/map_collect.rs#L20-L32).

**Comment by mathstuf** [comment] 2016-11-17 19:04
Ah, so each subdivision is folded individually; that makes sense for `ParallelIterator::fold`.

For `reduce`, it only needs the initial object once, and so could be done with an actual initial object, so it could (theoretically) use the `FnOnce` trait instead. Poking around a bit, it *seems* that the only changes that would be required are in the `reduce` module, but I'm not completely sure.

In any case, rewriting the code which made me open this issue into an iterator using `.chain` made the code much easier to work with, so now that I know how to do it, that works fine for me. A pointer from the `reduce` methods down to the `fold` method extra docs would be really helpful (I looked at the signatures, decided I needed `reduce` and ignored the `fold` docs).

**Comment by cuviper** [comment] 2016-11-17 19:14
Well, `reduce` is still operating in parallel, so it still can't share a single object.  Think of the splits like a branching tree, where some branches may be stolen into different threads.  The `reduce` will start collapsing those branches independently, then sending intermediate results back across threads if they were stolen.

This is why `reduce` ops have to be associative, btw.

**Comment by nikomatsakis** [comment] 2016-11-19 10:16
I'm going to close this issue -- this is all operating "by design". See also #94.

(In fact, in older versions, `reduce` took an initial object, but it had to be `Clone`, and we changed it to take a closure specifically because we didn't want to limit to clone-able things, but instead wanted "constructable" things.)

Note that you can call `reduce_with` in which case no initial value is required at all.

**Closed by nikomatsakis** 2016-11-19 10:16 UTC
